// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfZyiamASzalVWtXj-oPCm_z2zDItH7Q0',
    appId: '1:876311993857:web:c1929036258f9e8ffa6a00',
    messagingSenderId: '876311993857',
    projectId: 'd5ntodo',
    authDomain: 'd5ntodo.firebaseapp.com',
    storageBucket: 'd5ntodo.firebasestorage.app',
    measurementId: 'G-96W0D0X0FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABykStKrWbRuuYKe2MpDUrbk15kZMFWPA',
    appId: '1:876311993857:android:ed7384e1c343866cfa6a00',
    messagingSenderId: '876311993857',
    projectId: 'd5ntodo',
    storageBucket: 'd5ntodo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-LlSKhAMlpL0gNTaDZduqnGcJMo_8qII',
    appId: '1:876311993857:ios:4378094e8bab1349fa6a00',
    messagingSenderId: '876311993857',
    projectId: 'd5ntodo',
    storageBucket: 'd5ntodo.firebasestorage.app',
    iosBundleId: 'com.example.d5ntest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-LlSKhAMlpL0gNTaDZduqnGcJMo_8qII',
    appId: '1:876311993857:ios:4378094e8bab1349fa6a00',
    messagingSenderId: '876311993857',
    projectId: 'd5ntodo',
    storageBucket: 'd5ntodo.firebasestorage.app',
    iosBundleId: 'com.example.d5ntest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfZyiamASzalVWtXj-oPCm_z2zDItH7Q0',
    appId: '1:876311993857:web:036bf94f5086a158fa6a00',
    messagingSenderId: '876311993857',
    projectId: 'd5ntodo',
    authDomain: 'd5ntodo.firebaseapp.com',
    storageBucket: 'd5ntodo.firebasestorage.app',
    measurementId: 'G-L782Q422G1',
  );
}
